### ISSUE TITLE
keepSpiderfied: true does not work

### ISSUE THREAD

**Issue by dmccormack3** [jawj/OverlappingMarkerSpiderfier-Leaflet#24]
Hi,

I was hoping that spiderfied results would stay open when clicking between different results. This isn't the case using the following code however:

 var oms = new OverlappingMarkerSpiderfier(map, {  keepSpiderfied : true});

On a somewhat related note, is it possible to spiderfy each item automatically without a click?

**Comment by jawj** [comment]
I'm afraid neither of these things is easily possible, due to the way spiderfying works. See closed issues on the GMaps version:
https://github.com/jawj/OverlappingMarkerSpiderfier/issues/27
https://github.com/jawj/OverlappingMarkerSpiderfier/issues/3
