### ISSUE TITLE
Upload to CDNJS

### ISSUE THREAD

**Issue by kingy444** [jawj/OverlappingMarkerSpiderfier-Leaflet#37]
I have opened issue https://github.com/cdnjs/cdnjs/issues/10893 back in March but haven't had much activity in this area.

I want to use this in a project, but require the item to be in the CDNJS repository.

I can see that your original https://github.com/jawj/OverlappingMarkerSpiderfier is already in the repository. Hoping there might be something you can do to help get this into CDNJS quicker. I'm new to this whole GitHub thing and haven't had success so far.

**Comment by jawj** [comment]
Submitted https://github.com/cdnjs/cdnjs/pull/11227 so we'll see what happens.
