### ISSUE TITLE
A longer length of leg

### ISSUE THREAD

**Issue by dwiyatci** [jawj/OverlappingMarkerSpiderfier-Leaflet#38]
Is the spider's leg length customizable or hackable somehow? 🕷

**Comment by jawj** [comment]
Yes — experiment with the `circleFootSeparation`, `spiralFootSeparation`, `spiralLengthStart` and `spiralLengthFactor` options when creating your spiderfier instance.

**Comment by dwiyatci** [comment]
Thanks so much for the quick response, @jawj!

`circleFootSeparation` works nicely for me 🤘 

https://jsfiddle.net/glenn/2rvshhx1
