### ISSUE TITLE
angular 4 and overlappingMarkerSpiderfier

### ISSUE THREAD

**Issue by anandhuajayakumar** [jawj/OverlappingMarkerSpiderfier-Leaflet#39]
I am trying t use overlappingmarkerspiderfier with leaflet in my angular 4 application.
It worked with angular1 app, But the same is not for angular4
I installed the package with 
**`npm install npm i overlapping-marker-spiderfier`** 

But when I add 
**`var oms = new OverlappingMarkerSpiderfier(mmap);`**

It gives the error that  **`google not defined`**

When I add the **google-map api** to index.html the error is 
**`InvalidValueError: setMap: not an instance of Map; and not an instance of StreetViewPanorama`**

How can I solve this issue and get it working in angular4

**Comment by troddick** [comment]
Having the same issue. Were you able to solve this?

**Comment by anandhuajayakumar** [comment]
I did solve it.
I rewrote the existing javascript version of overlappingMarkerSpiderfier  for leaflet to typescript similar to the overlappingMarkerSpiderfier module.

**Comment by jawj** [comment]
Sounds great, @anandhuajayakumar! Closing ...

**Comment by AmitBuchnik** [comment]
hi @anandhuajayakumar 
can you share with me your solution?

**Comment by peterkowalsky333** [comment]
Very cool from you both.The one rewrote something, the other one closes, and the probme "IS SOLVED" !. Don't care about the other ones about the bug !!!
