### ISSUE TITLE
OverlappingMarkerSpiderfier for iOS

### ISSUE THREAD

**Issue by Niki4991** [jawj/OverlappingMarkerSpiderfier-Leaflet#40]
Hai Sir,

OverlappingMarkerSpiderfier is working ultimately in android platform. But the same is missing for iOS, so please can u post similar library for iOS as well.

Thanks

**Comment by wwwizzarrdry** [comment]
Just tested on android, ios, and desktop. Works fine on all platforms far as I can tell. 
What specifically isn't working on your iPhone?

**Comment by wwwizzarrdry** [comment]
This can be closed. It works fine on all platforms.
