### ISSUE TITLE
Programmatically trigger event

### ISSUE THREAD

**Issue by tverilytt** [jawj/OverlappingMarkerSpiderfier-Leaflet#51]
Hi!

Love the OMS, works great :-)

Just wanted to check if it is possible to programmatically trigger e.g. the "spiderfy" event?

Use case being populating a group of related markers, where one is kind of "current", and at that marker position, another marker is also present. Desire is to show both those markers initially...

Cheers
-jo

**Comment by jawj** [comment]
Have you tried simply programmatically 'clicking' the marker? https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click

**Comment by tverilytt** [comment]
@jawj Yes...found the way to do it in comment here: https://stackoverflow.com/a/38313970/4878494

marker.getElement().click()

Cheers
-jo
