### ISSUE TITLE
The demo page is dead

### ISSUE THREAD

**Issue by refeed** [jawj/OverlappingMarkerSpiderfier-Leaflet#53]
It returns 404

**Comment by jawj** [comment]
Thanks @refeed!

**Comment by adrianbj** [comment]
It's now dead because of https / http mismatch.

**Comment by jawj** [comment]
The link to the demo page is plain http for me, and still works. Are you using [HTTPS Everywhere](https://www.eff.org/https-everywhere) or something?

**Comment by adrianbj** [comment]
I was following the link to: https://jawj.github.io/OverlappingMarkerSpiderfier-Leaflet/demo.html - when I try to load it as http, it redirects to https. I am on Brave browser, but it lets me load other sites with http, so not sure why it's redirecting. Anyway, not to worry.
